portals:
  - name: "karriere_at"
    url: "https://www.karriere.at/"
    engine: KarriereHarvester
    requests_per_minute: 12
    retry_timeout: 5  # Wait 5 minutes before retrying after a server error
  - name: "stepstone_at"
    url: "https://www.stepstone.at/"
    requests_per_minute: 2
    retry_timeout: 15  # Wait 10 minutes before retrying after a server error
    engine: StepStoneHarvester
  - name: "stepstone_de"
    url: "https://www.stepstone.de/"
    requests_per_minute: 2
    retry_timeout: 15  # Wait 15 minutes before retrying after a server error
    engine: StepStoneHarvester
keywords:
  # We are using Python regular expressions to search for the keywords
  # https://docs.python.org/3/library/re.html
  - title: "Controller"
    search: controll
    case_sensitive: false
  - title: "Analyst"
    search: analyst
    case_sensitive: false
  - title: "Manager / Management"
    search: manag
    case_sensitive: false
  - title: "Projektentwicklung / Projektentwickler"
    search: projektentwickl
    case_sensitive: false
  - title: "Project development / Project developer"
    search: \bproject\s+develop
    case_sensitive: false
  - title: "Business developer / development"
    search: \bbusiness develop
    case_sensitive: false
  - title: "Recruiter / Recruiting"
    search: \brecruit
    case_sensitive: false
  - title: "HR"
    search: \bHR
    case_sensitive: true
  - title: "Human Resources"
    search: \bhuman\s+resourc
    case_sensitive: false
  - title: "People development"
    search: \bpeople\s+develop
    case_sensitive: false
  - title: "Personalentwicklung / Personalentwickler"
    search: \bpersonalentwickl
    case_sensitive: false
  - title: "Berater / Beratung"
    search: \bberat
    case_sensitive: false
  - title: "Consultant / Consulting"
    search: \bconsult
    case_sensitive: false
  - title: Associate
    search: \bassociate\b
    case_sensitive: false
  - title: "Markforscher / Marktforschung"
    search: \bmarktforsch
    case_sensitive: false
  - title: "Market research/er"
    search: \bmarket\s+research
    case_sensitive: false
  - title: "Marketing"
    search: .*marketing
    case_sensitive: false
  - title: "Vertrieb"
    search: vertrieb
    case_sensitive: false
  - title: "Sales"
    search: \bsales\b
    case_sensitive: false
  - title: "Finance / financial specialist / Finanz"
    search: \bfinan
    case_sensitive: false
  - title: "Communication"
    search: \bcommunication
    case_sensitive: false
  - title: "Kommunikation"
    search: kommunikation
    case_sensitive: false
  - title: "PR"
    search: \bPR
    case_sensitive: true
  - title: "Public relations"
    search: \bpublic\s+relations\b
    case_sensitive: false
  - title: "Leader"
    search: \bleader\b
    case_sensitive: false
  - title: "Team Lead"
    search: \bteam\s+lead\b
    case_sensitive: false
  - title: "Leitung"
    search: leitung\b
    case_sensitive: false
  - title: "Leiter"
    search: leiter
    case_sensitive: false
  - title: Tax advisor
    search: \btax\s+advi
    case_sensitive: false
  - title: "Steuerberater*in"
    search: \bsteuerberat
    case_sensitive: false
  - title: "Auditor"
    search: \baudit
    case_sensitive: false
  - title: "Wirtschaftsprüfer*in"
    search: \bwirtschaftsprüf
    case_sensitive: false
  - title: "Accountant"
    search: \baccount
    case_sensitive: false
  - title: "Buchhalter*in"
    search: buchhalt
    case_sensitive: false
filters:
  education_level:
    higher_education:
      catch_all: false
      case_sensitive: false
      pattern: '\babgeschloss.*studium\b|\bstudium.*abgeschlossen\b|\bbachelor.*studium\b|\bmasterstudium\b|\bgraduate.*degree\b|\buniversity.*degree\b'
      description: "Higher education positions"
    vocational:
      catch_all: false
      case_sensitive: false
      pattern: '\bberufsausbildung\b|\blehre\b|\bhandwerkliche.*ausbildung\b|\bhandwerkliche.*lehre\b|\bberufsbegleitend.*studium\b'
      description: "Vocational training positions"
    other_education:
      catch_all: false
      case_sensitive: false
      pattern: '.*'
      description: "Other education positions"
  job_type:
    full_time:
      catch_all: false
      case_sensitive: false
      pattern: '\bvollzeit\b|\bfull[\s-]*time\b'
    part_time:
      catch_all: false
      case_sensitive: false
      pattern: '\bteilzeit\b|\bpart[\s-]*time\b'
    internship:
      catch_all: false
      case_sensitive: false
      pattern: '\bpraktik\b|\binternship\b'
    other_job_type:
      catch_all: false
      case_sensitive: false
      pattern: '.*'
      description: "Other job types"

